version: '2'

services:
  server:
    restart: always
    image: 'myproject:latest'
    build: .
    environment:
      DATABASE_HOST: 'mysql'
      DATABASE_PORT: 3306
      DATABASE_NAME: 'test'
      DATABASE_USER: 'test'
      DATABASE_PASSWORD: 'test'
    ports:
      - '1337:1337'
    depends_on:
      - mysql
    
  mysql:
    restart: always
    image: 'mysql:5.7'
    # ports:
    #   - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    volumes:
      - './data/mysql:/var/lib/mysql'